import similarStudent from './similar-student.js'

describe('similar-student', () => {
  let student =  
	{
		"firstName": "Kaia",
		"lastName": "Bognet",
		"sex": "F",
		"facultyStudent": "",
		"newStudent": "",
		"medicalConcern": "",
		"hmp": "",
		"behavior": 1,
		"workEthic": 2,
		"mathBench": 69,
		"cogAT": 110,
		"elaTotal": 97,
		"mathTotal": 32,
		"asp": ""
	}
	let section = 
		{
		"sectionID": 1,
		"teacher": {
			"firstName": "A",
			"lastName": "Aa"
		},
		"students": [
			{
					"firstName": "Ella",
					"lastName": "Laski",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": "",
					"workEthic": 2,
					"mathBench": 95,
					"cogAT": "",
					"elaTotal": "",
					"mathTotal": "",
					"asp": ""
				  },
				  {
					"firstName": "Jackson",
					"lastName": "Snyder",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 83,
					"cogAT": 121,
					"elaTotal": 86,
					"mathTotal": 91,
					"asp": ""
				  },
				  {
					"firstName": "Micolas",
					"lastName": "Reggie",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 72,
					"cogAT": 110,
					"elaTotal": 63,
					"mathTotal": 79,
					"asp": ""
				  },
				  {
					"firstName": "Griffin",
					"lastName": "Patridge",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 86,
					"cogAT": 121,
					"elaTotal": 89,
					"mathTotal": 90,
					"asp": ""
				  },
				  {
					"firstName": "John",
					"lastName": "Niggel",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 83,
					"cogAT": "",
					"elaTotal": 89,
					"mathTotal": 66,
					"asp": ""
				  },
				  {
					"firstName": "Victor",
					"lastName": "Manzella",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 89,
					"cogAT": 128,
					"elaTotal": 98,
					"mathTotal": 80,
					"asp": ""
				  },
				  {
					"firstName": "Cameron",
					"lastName": "Blews",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": 1,
					"hmp": 1,
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 69,
					"cogAT": "",
					"elaTotal": 85,
					"mathTotal": 59,
					"asp": ""
				  },
				  {
					"firstName": "Evan",
					"lastName": "Eisenhard",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 75,
					"cogAT": 112,
					"elaTotal": 75,
					"mathTotal": 62,
					"asp": ""
				  },
				  {
					"firstName": "John",
					"lastName": "Fahrney",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 39,
					"cogAT": 90,
					"elaTotal": 41,
					"mathTotal": 14,
					"asp": ""
				  },
				  {
					"firstName": "Collin",
					"lastName": "Goff",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 2,
					"mathBench": 83,
					"cogAT": 130,
					"elaTotal": 94,
					"mathTotal": 98,
					"asp": ""
				  },
				  {
					"firstName": "Alex",
					"lastName": "Vergara",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 61,
					"cogAT": 103,
					"elaTotal": 61,
					"mathTotal": 43,
					"asp": ""
				  },
				  {
					"firstName": "Jaden",
					"lastName": "Morales",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 81,
					"cogAT": 117,
					"elaTotal": 89,
					"mathTotal": 82,
					"asp": ""
				  },
				  {
					"firstName": "Ryan",
					"lastName": "Doan",
					"sex": "M",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 75,
					"cogAT": 111,
					"elaTotal": 72,
					"mathTotal": 76,
					"asp": ""
				  },
				  {
					"firstName": "Grace",
					"lastName": "Spellacy",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 1,
					"mathBench": 36,
					"cogAT": 112,
					"elaTotal": 90,
					"mathTotal": 69,
					"asp": ""
				  },
				  {
					"firstName": "Madelyn",
					"lastName": "Robinson",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 78,
					"cogAT": 114,
					"elaTotal": 98,
					"mathTotal": 86,
					"asp": ""
				  },
				  {
					"firstName": "Nicole",
					"lastName": "Ayala",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 78,
					"cogAT": 120,
					"elaTotal": 94,
					"mathTotal": 72,
					"asp": ""
				  },
				  {
					"firstName": "Elizabeth",
					"lastName": "Duerholz",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": "",
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 75,
					"cogAT": 122,
					"elaTotal": 98,
					"mathTotal": 91,
					"asp": ""
				  },
				  {
					"firstName": "Seona",
					"lastName": "Hanna",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": "",
					"hmp": 1,
					"behavior": 2,
					"workEthic": 2,
					"mathBench": 92,
					"cogAT": 127,
					"elaTotal": 99,
					"mathTotal": 96,
					"asp": ""
				  },
				  {
					"firstName": "Isabella",
					"lastName": "Hilton",
					"sex": "F",
					"facultyStudent": "",
					"newStudent": "",
					"medicalConcern": 1,
					"hmp": 1,
					"behavior": 1,
					"workEthic": 1,
					"mathBench": 83,
					"cogAT": 114,
					"elaTotal": 70,
					"mathTotal": 80,
					"asp": ""
				  }
			]
		}
  it('runs', () => {
    similarStudent(student, section)
  })
})